;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	TeX-insert-backslash
	c-electric-colon
	c-electric-paren
	c-electric-star
	c-indent-line-or-region
	comment-region
	handle-switch-frame
	org-force-self-insert
	org-self-insert-command
	sh-assignment
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-semi&comma
	))
